name: flutter_hello_world
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  share: ^0.5.0
  connectivity: ^0.3.0
  cupertino_icons: ^0.1.0
  flutter_facebook_login: ^1.1.1
  fluro: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  assets:
    - resources/lang/vi.json
    - resources/lang/en.json
    - resources/images/login_background.jpg
    - resources/images/logo.png
  fonts:
    - family: Quicksand
      fonts:
        - asset: resources/fonts/Quicksand-Light.ttf
        - asset: resources/fonts/Quicksand-Medium.ttf
        - asset: resources/fonts/Quicksand-Bold.ttf
        - asset: resources/fonts/Quicksand-Regular.ttf
    - family: icon-clingme-2-0
      fonts:
        - asset: resources/fonts/icon-clingme-2-0.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
